In [26]:
import fastf1

f1_data = fastf1.get_session(2024, "Bahrain", "Race")
f1_data_british = fastf1.get_session(2026, "British", "Race")


f1_data.load()
f1_data_british.load()

core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '16', '63', '4', '44', '81', '14', '18', '24', '20', '3', '22', '23', '27', '31', '10', '77', '2']
core           INFO 	Loading data for British Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
_api        WARNING 	Driver 241: Position data is incomplete!
_api        WARNING 	Driver 242: Position data is incomplete!
_api        WARNING 	Driver 243: Position data is incomplete!
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
logger      WARNING 	Failed to load weather data!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 22 drivers: ['16', '63', '44', '1', '6', '30', '41', '5', '43', '10', '81', '87', '31', '11', '12', '77', '55', '14', '18', '3', '23', '27']

In [ ]:
laps = f1_data.laps
laps_british = f1_data_british.laps
tyre_data_british = f1_data_british

print(laps.shape)
print(laps_british.shape)

(1129, 31)
(1113, 31)

In [28]:
f1_data_british

2026 Season Round 9: British Grand Prix - Race

In [3]:
laps.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 01:01:37.489000,VER,1,0 days 00:01:37.284000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:41.266000,...,False,Red Bull Racing,0 days 00:59:59.911000,2024-03-02 15:03:42.342,12,1.0,False,,False,False
1,0 days 01:03:13.785000,VER,1,0 days 00:01:36.296000,2.0,1.0,NaT,NaT,0 days 00:00:30.916000,0 days 00:00:41.661000,...,False,Red Bull Racing,0 days 01:01:37.489000,2024-03-02 15:05:19.920,1,1.0,False,,False,True
2,0 days 01:04:50.538000,VER,1,0 days 00:01:36.753000,3.0,1.0,NaT,NaT,0 days 00:00:30.999000,0 days 00:00:41.966000,...,False,Red Bull Racing,0 days 01:03:13.785000,2024-03-02 15:06:56.216,1,1.0,False,,False,True
3,0 days 01:06:27.185000,VER,1,0 days 00:01:36.647000,4.0,1.0,NaT,NaT,0 days 00:00:30.931000,0 days 00:00:41.892000,...,False,Red Bull Racing,0 days 01:04:50.538000,2024-03-02 15:08:32.969,1,1.0,False,,False,True
4,0 days 01:08:04.358000,VER,1,0 days 00:01:37.173000,5.0,1.0,NaT,NaT,0 days 00:00:31.255000,0 days 00:00:42.056000,...,False,Red Bull Racing,0 days 01:06:27.185000,2024-03-02 15:10:09.616,1,1.0,False,,False,True

In [4]:
print(laps.columns.tolist())

['Time', 'Driver', 'DriverNumber', 'LapTime', 'LapNumber', 'Stint', 'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time', 'Sector1SessionTime', 'Sector2SessionTime', 'Sector3SessionTime', 'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST', 'IsPersonalBest', 'Compound', 'TyreLife', 'FreshTyre', 'Team', 'LapStartTime', 'LapStartDate', 'TrackStatus', 'Position', 'Deleted', 'DeletedReason', 'FastF1Generated', 'IsAccurate']

In [5]:
f1_data

2024 Season Round 1: Bahrain Grand Prix - Race

In [6]:
laps.info()

<class 'fastf1.core.Laps'>
RangeIndex: 1129 entries, 0 to 1128
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Time                1129 non-null   timedelta64[ns]
 1   Driver              1129 non-null   object
 2   DriverNumber        1129 non-null   object
 3   LapTime             1127 non-null   timedelta64[ns]
 4   LapNumber           1129 non-null   float64
 5   Stint               1129 non-null   float64
 6   PitOutTime          43 non-null     timedelta64[ns]
 7   PitInTime           43 non-null     timedelta64[ns]
 8   Sector1Time         1108 non-null   timedelta64[ns]
 9   Sector2Time         1129 non-null   timedelta64[ns]
 10  Sector3Time         1129 non-null   timedelta64[ns]
 11  Sector1SessionTime  1107 non-null   timedelta64[ns]
 12  Sector2SessionTime  1129 non-null   timedelta64[ns]
 13  Sector3SessionTime  1129 non-null   timedelta64[ns]
 14  SpeedI1             1129 non-null   float64
 15  SpeedI2             1129 non-null   float64
 16  SpeedFL             1086 non-null   float64
 17  SpeedST             1129 non-null   float64
 18  IsPersonalBest      1129 non-null   bool
 19  Compound            1129 non-null   object
 20  TyreLife            1129 non-null   float64
 21  FreshTyre           1129 non-null   bool
 22  Team                1129 non-null   object
 23  LapStartTime        1129 non-null   timedelta64[ns]
 24  LapStartDate        1129 non-null   datetime64[ns]
 25  TrackStatus         1129 non-null   object
 26  Position            1129 non-null   float64
 27  Deleted             1129 non-null   bool
 28  DeletedReason       1129 non-null   object
 29  FastF1Generated     1129 non-null   bool
 30  IsAccurate          1129 non-null   bool
dtypes: bool(5), datetime64[ns](1), float64(8), object(6), timedelta64[ns](11)
memory usage: 235.0+ KB

In [7]:
laps.isna().sum()

Time                     0
Driver                   0
DriverNumber             0
LapTime                  2
LapNumber                0
Stint                    0
PitOutTime            1086
PitInTime             1086
Sector1Time             21
Sector2Time              0
Sector3Time              0
Sector1SessionTime      22
Sector2SessionTime       0
Sector3SessionTime       0
SpeedI1                  0
SpeedI2                  0
SpeedFL                 43
SpeedST                  0
IsPersonalBest           0
Compound                 0
TyreLife                 0
FreshTyre                0
Team                     0
LapStartTime             0
LapStartDate             0
TrackStatus              0
Position                 0
Deleted                  0
DeletedReason            0
FastF1Generated          0
IsAccurate               0
dtype: int64

In [8]:
laps['Compound'].value_counts(dropna=False)

Compound
HARD    791
SOFT    338
Name: count, dtype: int64

In [9]:
laps["Driver"].value_counts()

Driver
VER    57
PER    57
SAI    57
LEC    57
RUS    57
NOR    57
HAM    57
PIA    57
ALO    57
STR    57
ZHO    56
MAG    56
RIC    56
TSU    56
ALB    56
HUL    56
OCO    56
GAS    56
BOT    56
SAR    55
Name: count, dtype: int64

In [10]:
print(type(laps))

<class 'fastf1.core.Laps'>

In [11]:
laps.groupby('Driver')['LapNumber'].max().sort_values(ascending=False)

Driver
ALO    57.0
PER    57.0
LEC    57.0
HAM    57.0
STR    57.0
VER    57.0
SAI    57.0
NOR    57.0
PIA    57.0
RUS    57.0
ALB    56.0
BOT    56.0
GAS    56.0
OCO    56.0
HUL    56.0
MAG    56.0
TSU    56.0
RIC    56.0
ZHO    56.0
SAR    55.0
Name: LapNumber, dtype: float64

In [12]:
laps.groupby("Driver")["Position"].last().sort_values()

Driver
VER     1.0
PER     2.0
SAI     3.0
LEC     4.0
RUS     5.0
NOR     6.0
HAM     7.0
PIA     8.0
ALO     9.0
STR    10.0
ZHO    11.0
MAG    12.0
RIC    13.0
TSU    14.0
ALB    15.0
HUL    16.0
OCO    17.0
GAS    18.0
BOT    19.0
SAR    20.0
Name: Position, dtype: float64

In [13]:
laps.columns

Index(['Time', 'Driver', 'DriverNumber', 'LapTime', 'LapNumber', 'Stint',
       'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time',
       'Sector1SessionTime', 'Sector2SessionTime', 'Sector3SessionTime',
       'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST', 'IsPersonalBest',
       'Compound', 'TyreLife', 'FreshTyre', 'Team', 'LapStartTime',
       'LapStartDate', 'TrackStatus', 'Position', 'Deleted', 'DeletedReason',
       'FastF1Generated', 'IsAccurate'],
      dtype='object')

In [14]:
laps[['Driver','LapNumber','Compound','TyreLife','FreshTyre']]

     Driver  LapNumber Compound  TyreLife  FreshTyre
0       VER        1.0     SOFT       4.0      False
1       VER        2.0     SOFT       5.0      False
2       VER        3.0     SOFT       6.0      False
3       VER        4.0     SOFT       7.0      False
4       VER        5.0     SOFT       8.0      False
...     ...        ...      ...       ...        ...
1124    SAR       51.0     SOFT      11.0       True
1125    SAR       52.0     SOFT      12.0       True
1126    SAR       53.0     SOFT      13.0       True
1127    SAR       54.0     SOFT      14.0       True
1128    SAR       55.0     SOFT      15.0       True

[1129 rows x 5 columns]

In [15]:
laps['Compound'].value_counts()

Compound
HARD    791
SOFT    338
Name: count, dtype: int64

In [16]:
laps['TyreLife'].value_counts()

TyreLife
4.0     62
5.0     62
6.0     62
7.0     62
8.0     62
9.0     62
10.0    60
11.0    58
12.0    57
13.0    53
14.0    52
3.0     52
2.0     52
1.0     52
15.0    49
16.0    44
17.0    40
18.0    39
19.0    35
20.0    32
21.0    24
22.0    17
23.0    13
24.0    10
25.0     6
26.0     6
27.0     2
28.0     2
29.0     1
30.0     1
Name: count, dtype: int64

In [17]:
laps.groupby("Compound")["TyreLife"].agg(["min", "max", "mean", "count"])

          min   max       mean  count
Compound
HARD      1.0  30.0  11.510746    791
SOFT      1.0  21.0   8.822485    338

In [18]:
laps['Stint']

0       1.0
1       1.0
2       1.0
3       1.0
4       1.0
       ...
1124    4.0
1125    4.0
1126    4.0
1127    4.0
1128    4.0
Name: Stint, Length: 1129, dtype: float64

In [19]:
laps.groupby(["Driver", "Stint", "Compound"])["TyreLife"].agg(["min", "max", "count"]).T

Driver     ALB               ALO               BOT               GAS  ...  \
Stint      1.0   2.0   3.0   1.0   2.0   3.0   1.0   2.0   3.0   1.0  ...
Compound  SOFT  HARD  HARD  SOFT  HARD  HARD  SOFT  HARD  HARD  SOFT  ...
min        1.0   1.0   1.0   4.0   1.0   1.0   1.0   1.0   1.0   1.0  ...
max       15.0  21.0  20.0  18.0  26.0  16.0  12.0  18.0  26.0  12.0  ...
count     15.0  21.0  20.0  15.0  26.0  16.0  12.0  18.0  26.0  12.0  ...

Driver     STR   TSU               VER              ZHO
Stint      3.0   1.0   2.0   3.0   1.0   2.0   3.0  1.0   2.0   3.0
Compound  HARD  SOFT  HARD  HARD  SOFT  HARD  SOFT SOFT  HARD  HARD
min        1.0   1.0   1.0   1.0   4.0   1.0   1.0  1.0   1.0   1.0
max       30.0  14.0  20.0  22.0  20.0  20.0  20.0  9.0  19.0  28.0
count     30.0  14.0  20.0  22.0  17.0  20.0  20.0  9.0  19.0  28.0

[3 rows x 63 columns]

In [20]:
# Your biggest Pandas trick

# Don't memorize 50 Pandas commands.

# Learn these questions → operations relationships:

# Question you want to answer	Typical operation
# How many?   - 	count(), value_counts()
# What categories exist?   - 	unique(), value_counts()
# What is the average?   - 	mean()
# What is the minimum/maximum?   - 	min(), max()
# How does X differ between groups?   - 	groupby()
# Show me only certain rows   - 	filtering
# Compare two datasets   - 	merge()
# Create a new variable	column assignment
# Relationship between variables   - 	correlation / plots
# Distribution of something   - 	histogram / descriptive statistics
# Find unusual values   - 	outlier analysis
# Change data structure   - 	pivot_table()

# You don't need to memorize syntax yet.

# You need to recognize:

# Question → appropriate analytical operation.

In [21]:
laps.columns

Index(['Time', 'Driver', 'DriverNumber', 'LapTime', 'LapNumber', 'Stint',
       'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time',
       'Sector1SessionTime', 'Sector2SessionTime', 'Sector3SessionTime',
       'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST', 'IsPersonalBest',
       'Compound', 'TyreLife', 'FreshTyre', 'Team', 'LapStartTime',
       'LapStartDate', 'TrackStatus', 'Position', 'Deleted', 'DeletedReason',
       'FastF1Generated', 'IsAccurate'],
      dtype='object')

In [22]:

laps[['Stint','Compound','TyreLife','Position']]

      Stint Compound  TyreLife  Position
0       1.0     SOFT       4.0       1.0
1       1.0     SOFT       5.0       1.0
2       1.0     SOFT       6.0       1.0
3       1.0     SOFT       7.0       1.0
4       1.0     SOFT       8.0       1.0
...     ...      ...       ...       ...
1124    4.0     SOFT      11.0      20.0
1125    4.0     SOFT      12.0      20.0
1126    4.0     SOFT      13.0      20.0
1127    4.0     SOFT      14.0      20.0
1128    4.0     SOFT      15.0      20.0

[1129 rows x 4 columns]

In [23]:
laps.columns

Index(['Time', 'Driver', 'DriverNumber', 'LapTime', 'LapNumber', 'Stint',
       'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time',
       'Sector1SessionTime', 'Sector2SessionTime', 'Sector3SessionTime',
       'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST', 'IsPersonalBest',
       'Compound', 'TyreLife', 'FreshTyre', 'Team', 'LapStartTime',
       'LapStartDate', 'TrackStatus', 'Position', 'Deleted', 'DeletedReason',
       'FastF1Generated', 'IsAccurate'],
      dtype='object')

In [24]:
laps[['Time','Driver','LapTime','LapNumber','SpeedI1','SpeedI2','SpeedFL','SpeedST','Compound','TyreLife','FreshTyre']]

,Time,Driver,LapTime,LapNumber,SpeedI1,SpeedI2,SpeedFL,SpeedST,Compound,TyreLife,FreshTyre
0,0 days 01:01:37.489000,VER,0 days 00:01:37.284000,1.0,234.0,250.0,276.0,251.0,SOFT,4.0,False
1,0 days 01:03:13.785000,VER,0 days 00:01:36.296000,2.0,232.0,248.0,276.0,287.0,SOFT,5.0,False
2,0 days 01:04:50.538000,VER,0 days 00:01:36.753000,3.0,231.0,243.0,276.0,290.0,SOFT,6.0,False
3,0 days 01:06:27.185000,VER,0 days 00:01:36.647000,4.0,233.0,253.0,276.0,290.0,SOFT,7.0,False
4,0 days 01:08:04.358000,VER,0 days 00:01:37.173000,5.0,231.0,245.0,276.0,289.0,SOFT,8.0,False
...,...,...,...,...,...,...,...,...,...,...,...
1124,0 days 02:25:37.835000,SAR,0 days 00:01:35.972000,51.0,233.0,261.0,281.0,291.0,SOFT,11.0,True
1125,0 days 02:27:13.822000,SAR,0 days 00:01:35.987000,52.0,233.0,262.0,281.0,292.0,SOFT,12.0,True
1126,0 days 02:28:49.910000,SAR,0 days 00:01:36.088000,53.0,232.0,261.0,281.0,292.0,SOFT,13.0,True
1127,0 days 02:30:29.524000,SAR,0 days 00:01:39.614000,54.0,185.0,261.0,282.0,292.0,SOFT,14.0,True
1128,0 days 02:32:05.733000,SAR,0 days 00:01:36.209000,55.0,232.0,260.0,281.0,296.0,SOFT,15.0,True

In [25]:
laps.columns

Index(['Time', 'Driver', 'DriverNumber', 'LapTime', 'LapNumber', 'Stint',
       'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time',
       'Sector1SessionTime', 'Sector2SessionTime', 'Sector3SessionTime',
       'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST', 'IsPersonalBest',
       'Compound', 'TyreLife', 'FreshTyre', 'Team', 'LapStartTime',
       'LapStartDate', 'TrackStatus', 'Position', 'Deleted', 'DeletedReason',
       'FastF1Generated', 'IsAccurate'],
      dtype='object')

In [ ]:
# so now i am making my own thesis and in that i ll be studying about the tyre and how the tyre affect the pit stoop and how the tyre health affect the lap time and performance